DROP DATABASE IF EXISTS DATAWAREHOUSE;
CREATE DATABASE DATAWAREHOUSE;

USE DATABASE DATAWAREHOUSE;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT CSV_STD
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';


--Creating Tables

DROP TABLE IF EXISTS CRM_CUST_INFO;
CREATE TABLE CRM_CUST_INFO (
    CST_ID             INT,
    CST_KEY            VARCHAR,
    CST_FIRSTNAME      VARCHAR,
    CST_LASTNAME       VARCHAR,
    CST_MARITAL_STATUS VARCHAR,
    CST_GNDR           VARCHAR,
    CST_CREATE_DATE    DATE
);

DROP TABLE IF EXISTS CRM_PRD_INFO;
CREATE TABLE CRM_PRD_INFO (
    PRD_ID       INT,
    PRD_KEY      VARCHAR,
    PRD_NM       VARCHAR,
    PRD_COST     INT,
    PRD_LINE     VARCHAR,
    PRD_START_DT TIMESTAMP_NTZ,
    PRD_END_DT   TIMESTAMP_NTZ
);

DROP TABLE IF EXISTS CRM_SALES_DETAILS;
CREATE TABLE CRM_SALES_DETAILS (
    SLS_ORD_NUM  VARCHAR,
    SLS_PRD_KEY  VARCHAR,
    SLS_CUST_ID  INT,
    SLS_ORDER_DT INT,  
    SLS_SHIP_DT  INT,
    SLS_DUE_DT   INT,
    SLS_SALES    INT,
    SLS_QUANTITY INT,
    SLS_PRICE    INT
);
  

DROP TABLE IF EXISTS ERP_LOC_A101;
CREATE TABLE ERP_LOC_A101 (
    CID   VARCHAR,
    CNTRY VARCHAR
);

DROP TABLE IF EXISTS ERP_CUST_AZ12;
CREATE TABLE ERP_CUST_AZ12 (
    CID   VARCHAR,
    BDATE DATE,
    GEN   VARCHAR
);

DROP TABLE IF EXISTS ERP_PX_CAT_G1V2;
CREATE TABLE ERP_PX_CAT_G1V2 (
    ID          VARCHAR,
    CAT         VARCHAR,
    SUBCAT      VARCHAR,
    MAINTENANCE VARCHAR
);

--S3 Integration

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<USE PERSONAL ARN ROLE>'
  STORAGE_ALLOWED_LOCATIONS = ('<USE PERSONAL S3 BUCKET LOCATION>');

  DESC STORAGE INTEGRATION S3_INT;

  CREATE OR REPLACE STAGE BRONZE_STAGE
  URL='<USE PERSONAL S3 BUCKET LOCATION>'
  STORAGE_INTEGRATION = S3_INT
  FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1);

  LIST @BRONZE_STAGE;

--CRM
TRUNCATE TABLE CRM_CUST_INFO;
COPY INTO CRM_CUST_INFO
FROM @BRONZE_STAGE/source_crm/cust_info.csv;

TRUNCATE TABLE CRM_PRD_INFO;
COPY INTO CRM_PRD_INFO
FROM @BRONZE_STAGE/source_crm/prd_info.csv;

TRUNCATE TABLE CRM_SALES_DETAILS;
COPY INTO CRM_SALES_DETAILS
FROM @BRONZE_STAGE/source_crm/sales_details.csv;

-- ERP
TRUNCATE TABLE ERP_LOC_A101;
COPY INTO ERP_LOC_A101
FROM @BRONZE_STAGE/source_erp/LOC_A101.csv;

TRUNCATE TABLE ERP_CUST_AZ12;
COPY INTO ERP_CUST_AZ12
FROM @BRONZE_STAGE/source_erp/CUST_AZ12.csv;

TRUNCATE TABLE ERP_PX_CAT_G1V2;
COPY INTO ERP_PX_CAT_G1V2
FROM @BRONZE_STAGE/source_erp/PX_CAT_G1V2.csv;

--SELECT * FROM ERP_PX_CAT_G1V2

