USE DATABASE DATAWAREHOUSE;
USE SCHEMA SILVER;

DROP TABLE IF EXISTS CRM_CUST_INFO;
CREATE TABLE CRM_CUST_INFO (
    CST_ID             INT,
    CST_KEY            VARCHAR,
    CST_FIRSTNAME      VARCHAR,
    CST_LASTNAME       VARCHAR,
    CST_MARITAL_STATUS VARCHAR,
    CST_GNDR           VARCHAR,
    CST_CREATE_DATE    DATE,
    DWH_CREATE_DATE    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


DROP TABLE IF EXISTS CRM_PRD_INFO;
CREATE TABLE CRM_PRD_INFO (
    PRD_ID          INT,
    CAT_ID          VARCHAR,
    PRD_KEY         VARCHAR,
    PRD_NM          VARCHAR,
    PRD_COST        INT,
    PRD_LINE        VARCHAR,
    PRD_START_DT    DATE,
    PRD_END_DT      DATE,
    DWH_CREATE_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS CRM_SALES_DETAILS;
CREATE TABLE CRM_SALES_DETAILS (
    SLS_ORD_NUM     VARCHAR,
    SLS_PRD_KEY     VARCHAR,
    SLS_CUST_ID     INT,
    SLS_ORDER_DT    DATE,
    SLS_SHIP_DT     DATE,
    SLS_DUE_DT      DATE,
    SLS_SALES       INT,
    SLS_QUANTITY    INT,
    SLS_PRICE       INT,
    DWH_CREATE_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS ERP_LOC_A101;
CREATE TABLE ERP_LOC_A101 (
    CID             VARCHAR,
    CNTRY           VARCHAR,
    DWH_CREATE_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS ERP_CUST_AZ12;
CREATE TABLE ERP_CUST_AZ12 (
    CID             VARCHAR,
    BDATE           DATE,
    GEN             VARCHAR,
    DWH_CREATE_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DROP TABLE IF EXISTS ERP_PX_CAT_G1V2;
CREATE TABLE ERP_PX_CAT_G1V2 (
    ID              VARCHAR,
    CAT             VARCHAR,
    SUBCAT          VARCHAR,
    MAINTENANCE     VARCHAR,
    DWH_CREATE_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


--CRM_CUST_INFO
TRUNCATE TABLE CRM_CUST_INFO;

INSERT INTO CRM_CUST_INFO (
    CST_ID,
    CST_KEY,
    CST_FIRSTNAME,
    CST_LASTNAME,
    CST_MARITAL_STATUS,
    CST_GNDR,
    CST_CREATE_DATE
)
SELECT
    CST_ID,
    CST_KEY,
    TRIM(CST_FIRSTNAME) AS CST_FIRSTNAME,
    TRIM(CST_LASTNAME)  AS CST_LASTNAME,
    CASE 
        WHEN UPPER(TRIM(CST_MARITAL_STATUS)) = 'S' THEN 'Single'
        WHEN UPPER(TRIM(CST_MARITAL_STATUS)) = 'M' THEN 'Married'
        ELSE 'n/a'
    END AS CST_MARITAL_STATUS,
    CASE 
        WHEN UPPER(TRIM(CST_GNDR)) = 'F' THEN 'Female'
        WHEN UPPER(TRIM(CST_GNDR)) = 'M' THEN 'Male'
        ELSE 'n/a'
    END AS CST_GNDR,
    CST_CREATE_DATE
FROM (
    SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY CST_ID ORDER BY CST_CREATE_DATE DESC) AS RN
    FROM DATAWAREHOUSE.BRONZE.CRM_CUST_INFO
    WHERE CST_ID IS NOT NULL
) T
WHERE RN = 1;

--CRM_PRD_INFO
TRUNCATE TABLE CRM_PRD_INFO;

INSERT INTO CRM_PRD_INFO (
    PRD_ID,
    CAT_ID,
    PRD_KEY,
    PRD_NM,
    PRD_COST,
    PRD_LINE,
    PRD_START_DT,
    PRD_END_DT
)
SELECT
    PRD_ID,
    REPLACE(SUBSTRING(PRD_KEY, 1, 5), '-', '_') AS CAT_ID,
    SUBSTRING(PRD_KEY, 7)                        AS PRD_KEY,
    PRD_NM,
    IFNULL(PRD_COST, 0)                          AS PRD_COST,
    CASE 
        WHEN UPPER(TRIM(PRD_LINE)) = 'M' THEN 'Mountain'
        WHEN UPPER(TRIM(PRD_LINE)) = 'R' THEN 'Road'
        WHEN UPPER(TRIM(PRD_LINE)) = 'S' THEN 'Other Sales'
        WHEN UPPER(TRIM(PRD_LINE)) = 'T' THEN 'Touring'
        ELSE 'n/a'
    END AS PRD_LINE,
    CAST(PRD_START_DT AS DATE) AS PRD_START_DT,
    DATEADD(
        DAY,
        -1,
        LEAD(CAST(PRD_START_DT AS DATE)) OVER (PARTITION BY SUBSTRING(PRD_KEY, 7) ORDER BY PRD_START_DT)
    ) AS PRD_END_DT
FROM DATAWAREHOUSE.BRONZE.CRM_PRD_INFO;


--CRM_SALES_DETAILS
TRUNCATE TABLE CRM_SALES_DETAILS;

INSERT INTO CRM_SALES_DETAILS (
    SLS_ORD_NUM,
    SLS_PRD_KEY,
    SLS_CUST_ID,
    SLS_ORDER_DT,
    SLS_SHIP_DT,
    SLS_DUE_DT,
    SLS_SALES,
    SLS_QUANTITY,
    SLS_PRICE
)
SELECT 
    SLS_ORD_NUM,
    SLS_PRD_KEY,
    SLS_CUST_ID,

    CASE 
        WHEN SLS_ORDER_DT = 0 
          OR LENGTH(TO_CHAR(SLS_ORDER_DT)) != 8 THEN NULL
        ELSE TO_DATE(TO_CHAR(SLS_ORDER_DT), 'YYYYMMDD')
    END AS SLS_ORDER_DT,

    CASE 
        WHEN SLS_SHIP_DT = 0 
          OR LENGTH(TO_CHAR(SLS_SHIP_DT)) != 8 THEN NULL
        ELSE TO_DATE(TO_CHAR(SLS_SHIP_DT), 'YYYYMMDD')
    END AS SLS_SHIP_DT,

    CASE 
        WHEN SLS_DUE_DT = 0 
          OR LENGTH(TO_CHAR(SLS_DUE_DT)) != 8 THEN NULL
        ELSE TO_DATE(TO_CHAR(SLS_DUE_DT), 'YYYYMMDD')
    END AS SLS_DUE_DT,

    CASE 
        WHEN SLS_SALES IS NULL 
          OR SLS_SALES <= 0 
          OR SLS_SALES != SLS_QUANTITY * ABS(SLS_PRICE)
            THEN SLS_QUANTITY * ABS(SLS_PRICE)
        ELSE SLS_SALES
    END AS SLS_SALES,

    SLS_QUANTITY,

    CASE 
        WHEN SLS_PRICE IS NULL 
          OR SLS_PRICE <= 0 
            THEN CASE 
                     WHEN SLS_QUANTITY = 0 THEN NULL
                     ELSE SLS_SALES / NULLIF(SLS_QUANTITY, 0)
                 END
        ELSE SLS_PRICE
    END AS SLS_PRICE

FROM DATAWAREHOUSE.BRONZE.CRM_SALES_DETAILS;

--ERP_CUST_AZ12
TRUNCATE TABLE ERP_CUST_AZ12;

INSERT INTO ERP_CUST_AZ12 (
    CID,
    BDATE,
    GEN
)
SELECT
    CASE
        WHEN CID LIKE 'NAS%' THEN SUBSTRING(CID, 4)
        ELSE CID
    END AS CID,
    CASE
        WHEN BDATE > CURRENT_DATE THEN NULL
        ELSE BDATE
    END AS BDATE,
    CASE
        WHEN UPPER(TRIM(GEN)) IN ('F', 'FEMALE') THEN 'Female'
        WHEN UPPER(TRIM(GEN)) IN ('M', 'MALE')   THEN 'Male'
        ELSE 'n/a'
    END AS GEN
FROM DATAWAREHOUSE.BRONZE.ERP_CUST_AZ12;

-- ERP_LOC_A101
TRUNCATE TABLE ERP_LOC_A101;

INSERT INTO ERP_LOC_A101 (
    CID,
    CNTRY
)
SELECT
    REPLACE(CID, '-', '') AS CID,
    CASE
        WHEN TRIM(CNTRY) = 'DE'          THEN 'Germany'
        WHEN TRIM(CNTRY) IN ('US','USA') THEN 'United States'
        WHEN CNTRY IS NULL OR TRIM(CNTRY) = '' THEN 'n/a'
        ELSE TRIM(CNTRY)
    END AS CNTRY
FROM DATAWAREHOUSE.BRONZE.ERP_LOC_A101;

-- ERP_PX_CAT_G1V2
TRUNCATE TABLE ERP_PX_CAT_G1V2;

INSERT INTO ERP_PX_CAT_G1V2 (
    ID,
    CAT,
    SUBCAT,
    MAINTENANCE
)
SELECT
    ID,
    CAT,
    SUBCAT,
    MAINTENANCE
FROM DATAWAREHOUSE.BRONZE.ERP_PX_CAT_G1V2;

